### ISSUE TITLE
导出excel报空指针

### ISSUE THREAD

**Issue by LY-GO** [zhangdaiscott/JimuReport#131]
![Snipaste_2021-03-18_16-52-01](https://user-images.githubusercontent.com/67543312/111598627-632ee400-880a-11eb-8467-f8b711534ff3.png)
![VEH 3PH7YIF W`_BPHN1ALK](https://user-images.githubusercontent.com/67543312/111598643-66c26b00-880a-11eb-8fce-99ffce43cc02.jpg)

##### 版本号：
1.2.0

##### 问题描述：

1.导出excel报空指针
2.sql解析时,sql语句写错,点击sql解析后,提示无数据;待检查sql语句拼写正确后,拿到解析字段;在切换预览时后台报错为SQL语句错误;难道是走了缓存
##### 截图&代码：

![HB2)UECW3X~UK}GPXDVW473](https://user-images.githubusercontent.com/67543312/111598540-498d9c80-880a-11eb-9445-0f8e95ae06ef.jpg)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by 1298191366** [comment]
经debug调试这一段为空，不会报空指针异常

**Comment by 1298191366** [comment]
或者有其它特殊的操作

**Comment by 1298191366** [comment]
第二个问题：请把sql语句怎样写的粘贴出来，因解析和预览不是一个逻辑，故可能存在问题

**Comment by zhangdaiscott** [comment]
请升级到最新版本再测试
```
<dependency>
    <groupId>org.jeecgframework.jimureport</groupId>
    <artifactId>spring-boot-starter-jimureport</artifactId>
    <version>1.3.0-beta3</version>
</dependency>
```
http://report.jeecg.com/2078875

**Comment by yangjunzhou861012** [comment]
> 请升级到最新版本再测试
> 
> ```
> <dependency>
>     <groupId>org.jeecgframework.jimureport</groupId>
>     <artifactId>spring-boot-starter-jimureport</artifactId>
>     <version>1.3.0-beta3</version>
> </dependency>
> ```
> 
> http://report.jeecg.com/2078875

升级到此版本依旧会报空指针异常，我这测试，如果是excel中有样式（json格式数据是包含style），则会报空指针异常，如果没有样式，则是正常下载
java.lang.NullPointerException
	at org.jeecg.modules.jmreport.desreport.service.a.j.a(JmReportExportExcelImpl.java:308)
	at org.jeecg.modules.jmreport.desreport.service.a.j.a(JmReportExportExcelImpl.java:257)
	at org.jeecg.modules.jmreport.desreport.service.a.j.a(JmReportExportExcelImpl.java:165)
	at org.jeecg.modules.jmreport.desreport.service.a.j.exportExcel(JmReportExportExcelImpl.java:57)
	at org.jeecg.modules.jmreport.desreport.a.a.a(DesignReportController.java:897)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:215)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:142)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:102)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:895)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:800)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1038)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:942)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:998)
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:901)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:665)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:875)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:750)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:200)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:101)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.alibaba.druid.support.http.WebStatFilter.doFilter(WebStatFilter.java:124)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:320)
	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:127)
	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:91)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:119)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:137)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:111)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:170)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.security.web.savedrequest.RequestCacheAwareFilter.doFilter(RequestCacheAwareFilter.java:63)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at com.superDev.modules.security.security.TokenFilter.doFilter(TokenFilter.java:75)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.web.filter.CorsFilter.doFilterInternal(CorsFilter.java:96)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:116)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.security.web.header.HeaderWriterFilter.doFilterInternal(HeaderWriterFilter.java:66)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:105)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:56)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:215)
	at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:178)
	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:357)
	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:270)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:200)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:490)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:408)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:770)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1415)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)

**Comment by 1298191366** [comment]
> {"loopBlockList":[],"area":false,"printElWidth":200,"excel_config_id":"1376203061910966272","printElHeight":1047,"rows":{"0":{"height":57.5,"cells":{"0":{"style":1,"text":"序号"},"1":{"style":2,"text":"姓名"}}},"1":{"height":37.5,"cells":{"0":{"style":3,"text":"1"},"1":{"style":4,"text":"刘德华"}}},"2":{"height":37.5,"cells":{"0":{"style":5,"text":"2"},"1":{"style":6,"text":"张学友"}}},"3":{"height":37.5,"cells":{"0":{"style":7,"text":"3"},"1":{"style":8,"text":"李连杰"}}},"4":{"height":37.5,"cells":{"0":{"style":9,"text":"4"},"1":{"style":10,"text":"周星驰"}}},"len":100},"dbexps":[],"toolPrintSizeObj":{"printType":"A4","widthPx":718,"heightPx":1047},"dicts":[],"freeze":"A1","dataRectWidth":200,"displayConfig":{},"background":false,"name":"sheet1","autofilter":{},"styles":{"1":{"border":{"left":["thin","#0"],"bottom":["thin","#0"],"right":["thin","#0"]},"align":"center","font":{"size":10}},"2":{"border":{"left":["thin","#0"],"bottom":["thin","#0"],"right":["thin","#0"]},"align":"center","font":{"size":10}},"3":{"border":{"top":["thin","#0"],"left":["thin","#0"],"bottom":["thin","#0"]},"align":"center","font":{"size":10}},"4":{"border":{"top":["thin","#0"],"left":["thin","#0"],"bottom":["thin","#0"],"right":["thin","#0"]},"align":"center","font":{"size":10}},"5":{"border":{"top":["thin","#0"],"left":["thin","#0"],"bottom":["thin","#0"]},"align":"center","font":{"size":10}},"6":{"border":{"top":["thin","#0"],"left":["thin","#0"],"bottom":["thin","#0"],"right":["thin","#0"]},"align":"center","font":{"size":10}},"7":{"border":{"top":["thin","#0"],"left":["thin","#0"],"bottom":["thin","#0"]},"align":"center","font":{"size":10}},"8":{"border":{"top":["thin","#0"],"left":["thin","#0"],"bottom":["thin","#0"],"right":["thin","#0"]},"align":"center","font":{"size":10}},"9":{"border":{"top":["thin","#0"],"left":["thin","#0"],"bottom":["thin","#0"]},"align":"center","font":{"size":10}},"10":{"border":{"top":["thin","#0"],"left":["thin","#0"],"bottom":["thin","#0"],"right":["thin","#0"]},"align":"center","font":{"size":10}}},"validations":[],"cols":{"len":50},"merges":[]}

你确认是这个json吗，我这里可以导出没有报错，我这里就出现了没有边框没有样式的bug，已修复
![image](https://user-images.githubusercontent.com/30997828/112803489-ea4f4800-90a5-11eb-9b3c-20af6525acaa.png)

**Comment by 1298191366** [comment]
excel报空指针已复现且修改，待新版本发布
