### ISSUE TITLE
集成demo 运行后 预览报错问题

### ISSUE THREAD

**Issue by lcc-java** [zhangdaiscott/JimuReport#174]
##### 版本号：

1.3.1-beta2
##### 问题描述：

预览报错
##### 截图&代码：

![image](https://user-images.githubusercontent.com/53068551/113798422-bcdd5b00-9785-11eb-89ba-f2b86c6ef134.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
后台详细日志贴一下

**Comment by lcc-java** [comment]
2021-04-07 11:26:17.976 DEBUG 9624 --- [nio-9991-exec-8] o.j.m.j.c.i.JimuReportInterceptor        : JimuReportInterceptor check requestPath = /jmreport/view/1334378897302753280
2021-04-07 11:26:17.976 DEBUG 9624 --- [nio-9991-exec-8] o.j.m.j.common.util.ViewFreemarker       : Freemarker loading：jmreport/desreport/view.ftl
2021-04-07 11:26:18.254 DEBUG 9624 --- [nio-9991-exec-2] o.j.m.j.c.i.JimuReportInterceptor        : JimuReportInterceptor check requestPath = /jmreport/getQueryInfo
2021-04-07 11:26:18.256 DEBUG 9624 --- [nio-9991-exec-1] o.j.m.j.c.i.JimuReportInterceptor        : JimuReportInterceptor check requestPath = /jmreport/checkParam/1334378897302753280
2021-04-07 11:26:18.258 DEBUG 9624 --- [nio-9991-exec-3] o.j.m.j.c.i.JimuReportInterceptor        : JimuReportInterceptor check requestPath = /jmreport/addViewCount/1334378897302753280
2021-04-07 11:26:18.261 DEBUG 9624 --- [nio-9991-exec-3] o.jeecg.modules.jmreport.desreport.a.a   : 新增浏览次数：448,>>1334378897302753280
2021-04-07 11:26:18.275 DEBUG 9624 --- [nio-9991-exec-4] o.j.m.j.c.i.JimuReportInterceptor        : JimuReportInterceptor check requestPath = /jmreport/show
2021-04-07 11:26:18.276 DEBUG 9624 --- [nio-9991-exec-4] o.j.m.jmreport.desreport.service.a.d     : ============EXCEL JSON数据查询==========
2021-04-07 11:26:18.278 DEBUG 9624 --- [nio-9991-exec-4] o.j.m.jmreport.desreport.service.a.d     : ====配置的json字符串==={"loopBlockList":[],"area":false,"printElWidth":718,"excel_config_id":"1334378897302753280","printElHeight":1047,"rows":{"0":{"cells":{"1":{"text":"区域销售表","merge":[0,22],"style":10},"2":{"style":10},"3":{"style":10},"4":{"style":10},"5":{"style":10},"6":{"style":10},"7":{"style":10},"8":{"style":10},"9":{"style":10},"10":{"style":10},"11":{"style":10},"12":{"style":10},"13":{"style":10},"14":{"style":10},"15":{"style":10},"16":{"style":10},"17":{"style":10},"18":{"style":10},"19":{"style":10},"20":{"style":10},"21":{"style":10},"22":{"style":10},"23":{"style":10}},"height":72},"1":{"cells":{"0":{"style":64},"1":{"text":"区域","merge":[1,0],"style":65},"2":{"text":"省份","merge":[1,0],"style":65},"3":{"text":"1月","merge":[0,2],"style":65},"4":{"style":66,"text":" "},"5":{"style":66,"text":" "},"6":{"text":"2月","merge":[0,2],"style":65},"7":{"style":66,"text":" "},"8":{"style":66,"text":" "},"9":{"text":"3月","merge":[0,2],"style":65},"10":{"style":66,"text":" "},"11":{"style":66,"text":" "},"12":{"text":"4月","merge":[0,2],"style":65},"13":{"style":66,"text":" "},"14":{"style":66,"text":" "},"15":{"text":"5月","merge":[0,2],"style":65},"16":{"style":66,"text":" "},"17":{"style":66,"text":" "},"18":{"text":"6月","merge":[0,2],"style":65},"19":{"style":66,"text":" "},"20":{"style":66,"text":" "},"21":{"text":"总合计","merge":[0,2],"style":65},"22":{"style":66,"text":" "},"23":{"style":66,"text":" "},"24":{"style":64},"25":{"style":64}},"height":22},"2":{"cells":{"0":{"style":64},"1":{"style":66,"text":" "},"2":{"style":65,"text":" "},"3":{"text":"销售额","style":65},"4":{"text":"搭赠","style":65},"5":{"text":"比例","style":65},"6":{"text":"销售额","style":65},"7":{"text":"搭赠","style":65},"8":{"text":"比例","style":65},"9":{"text":"销售额","style":65},"10":{"text":"搭赠","style":65},"11":{"text":"比例","style":65},"12":{"text":"销售额","style":65},"13":{"text":"搭赠","style":65},"14":{"text":"比例","style":65},"15":{"text":"销售额","style":65},"16":{"text":"搭赠","style":65},"17":{"text":"比例","style":65},"18":{"text":"销售额","style":65},"19":{"text":"搭赠","style":65},"20":{"text":"比例","style":65},"21":{"text":"销售额","style":65},"22":{"text":"搭赠","style":65},"23":{"text":"比例","style":65},"24":{"style":64},"25":{"style":64}},"height":24},"3":{"cells":{"0":{"style":67},"1":{"text":"#{quyuxiaoshou.group(region)}","style":52,"aggregate":"group"},"2":{"text":"#{quyuxiaoshou.province}","style":53},"3":{"text":"#{quyuxiaoshou.sales_1}","style":17},"4":{"text":"#{quyuxiaoshou.gift_1}","style":17},"5":{"text":"#{quyuxiaoshou.proportion_1}","style":17},"6":{"text":"#{quyuxiaoshou.sales_2}","style":17},"7":{"text":"#{quyuxiaoshou.gift_2}","style":17},"8":{"text":"#{quyuxiaoshou.proportion_2}","style":17},"9":{"text":"#{quyuxiaoshou.sales_3}","style":17},"10":{"text":"#{quyuxiaoshou.gift_3}","style":17},"11":{"text":"#{quyuxiaoshou.proportion_3}","style":17},"12":{"text":"#{quyuxiaoshou.sales_4}","style":17},"13":{"text":"#{quyuxiaoshou.gift_4}","style":17},"14":{"text":"#{quyuxiaoshou.proportion_4}","style":17},"15":{"text":"#{quyuxiaoshou.sales_5}","style":17},"16":{"text":"#{quyuxiaoshou.gift_5}","style":17},"17":{"text":"#{quyuxiaoshou.proportion_5}","style":15},"18":{"text":"#{quyuxiaoshou.sales_6}","style":15},"19":{"text":"#{quyuxiaoshou.gift_6}","style":15},"20":{"text":"#{quyuxiaoshou.proportion_6}","style":15},"21":{"text":"#{quyuxiaoshou.sales_z}","style":15},"22":{"text":"#{quyuxiaoshou.gift_z}","style":15},"23":{"text":"#{quyuxiaoshou.proportion_z}","style":15},"24":{"style":67},"25":{"style":67}},"isDrag":true,"height":56},"4":{"cells":{"0":{"style":64},"1":{"style":39,"text":"总计","merge":[0,1]},"3":{"style":68,"text":"=SUM(D4)"},"4":{"style":69,"text":"=SUM(E4)"},"5":{"style":70,"text":"=SUM(F4)"},"6":{"style":69,"text":"=SUM(G4)"},"7":{"style":69,"text":"=SUM(H4)"},"8":{"style":70,"text":"=SUM(I4)"},"9":{"style":69,"text":"=SUM(J4)"},"10":{"style":69,"text":"=SUM(K4)"},"11":{"style":70,"text":"=SUM(L4)"},"12":{"style":69,"text":"=SUM(M4)"},"13":{"style":69,"text":"=SUM(N4)"},"14":{"style":70,"text":"=SUM(O4)"},"15":{"style":69,"text":"=SUM(P4)"},"16":{"style":69,"text":"=SUM(Q4)"},"17":{"style":70,"text":"=SUM(R4)"},"18":{"style":69,"text":"=SUM(S4)"},"19":{"style":69,"text":"=SUM(T4)"},"20":{"style":70,"text":"=SUM(U4)"},"21":{"style":69,"text":"=SUM(V4)"},"22":{"style":69,"text":"=SUM(W4)"},"23":{"style":69,"text":"=SUM(X4)"},"24":{"style":64},"25":{"style":64}},"height":38},"len":100},"dbexps":[],"toolPrintSizeObj":{"printType":"A4","widthPx":718,"heightPx":1047},"dicts":[],"groupField":"quyuxiaoshou.region","freeze":"A1","dataRectWidth":1554,"background":false,"name":"sheet1","autofilter":{},"styles":[{"align":"center"},{"align":"center","bgcolor":""},{"align":"center","bgcolor":"#02a274"},{"align":"center","bgcolor":"#02a274","color":"#ffffff"},{"bgcolor":"#02a274"},{"align":"center","bgcolor":"#02a274","color":"#ffffff","border":{"bottom":["thin","bfbfbf"],"top":["thin","bfbfbf"],"left":["thin","bfbfbf"],"right":["thin","bfbfbf"]}},{"border":{"bottom":["thin","bfbfbf"],"top":["thin","bfbfbf"],"left":["thin","bfbfbf"],"right":["thin","bfbfbf"]}},{"align":"center","bgcolor":"#02a274","color":"#ffffff","border":{"bottom":["thin","#bfbfbf"],"top":["thin","#bfbfbf"],"left":["thin","#bfbfbf"],"right":["thin","#bfbfbf"]}},{"border":{"bottom":["thin","#bfbfbf"],"top":["thin","#bfbfbf"],"left":["thin","#bfbfbf"],"right":["thin","#bfbfbf"]}},{"align":"center","font":{"size":16}},{"align":"center","font":{"size":16,"bold":true}},{"border":{"bottom":["thin","#bfbfbf"],"top":["thin","#bfbfbf"],"left":["thin","#bfbfbf"],"right":["thin","#bfbfbf"]},"font":{"size":8}},{"border":{"bottom":["thin","#bfbfbf"],"top":["thin","#bfbfbf"],"left":["thin","#bfbfbf"],"right":["thin","#bfbfbf"]},"font":{"size":8},"align":"center"},{"border":{"bottom":["thin","#bfbfbf"],"top":["thin","#bfbfbf"],"left":["thin","#bfbfbf"],"right":["thin","#bfbfbf"]},"font":{"size":8,"name":"宋体"},"align":"center"},{"border":{"bottom":["thin","#bfbfbf"],"top":["thin","#bfbfbf"],"left":["thin","#bfbfbf"],"right":["thin","#bfbfbf"]},"font":{"size":8,"name":"隶书"},"align":"center"},{"border":{"bottom":["thin","#bfbfbf"],"top":["thin","#bfbfbf"],"left":["thin","#bfbfbf"],"right":["thin","#bfbfbf"]},"font":{"size":8,"name":"Microsoft YaHei"},"align":"center"},{"border":{"bottom":["thin","#bfbfbf"],"top":["thin","#bfbfbf"],"left":["thin","#bfbfbf"],"right":["thin","#bfbfbf"]},"font":{"size":8,"name":"Microsoft YaHei"},"align":"center","color":"#7f7f7f"},{"border":{"bottom":["thin","#bfbfbf"],"top":["thin","#bfbfbf"],"left":["thin","#bfbfbf"],"right":["thin","#bfbfbf"]},"font":{"size":8,"name":"Microsoft YaHei"},"align":"center","color":"#262626"},{"align":"center","bgcolor":"#02a274","color":"#ffffff","border":{"bottom":["thin","#bfbfbf"],"top":["thin","#bfbfbf"],"left":["thin","#bfbfbf"],"right":["thin","#bfbfbf"]},"font":{"bold":true}},{"align":"center","bgcolor":"#02a274","color":"#ffffff","font":{"bold":true}},{"border":{"bottom":["thin","#bfbfbf"],"top":["thin","#bfbfbf"],"left":["thin","#bfbfbf"],"right":["thin","#bfbfbf"]},"font":{"size":8,"name":"Microsoft YaHei"},"align":"center","color":"#262626","bgcolor":"#"},{"border":{"bottom":["thin","#bfbfbf"],"top":["thin","#bfbfbf"],"left":["thin","#bfbfbf"],"right":["thin","#bfbfbf"]},"font":{"size":8,"name":"Microsoft YaHei"},"align":"center","color":"#262626","bgcolor":"#f1f9f6"},{"border":{"bottom":["thin","#bfbfbf"],"top":["thin","#bfbfbf"],"left":["thin","#bfbfbf"],"right":["thin","#bfbfbf"]},"font":{"size":8,"name":"Microsoft YaHei"},"align":"center","color":"#262626","bgcolor":"#ddefe8"},{"align":"center","bgcolor":"#02a274","color":"#ffffff","border":{"bottom":["thin","#bfbfbf"],"top":["thin","#bfbfbf"],"left":["thin","#bfbfbf"],"right":["thin","#bfbfbf"]},"font":{"bold":true,"size":9}},{"align":"center","bgcolor":"#02a274","color":"#ffffff","font":{"bold":true,"size":9}},{"border":{"bottom":["thin","#bfbfbf"],"top":["thin","#bfbfbf"],"left":["thin","#bfbfbf"],"right":["thin","#bfbfbf"]},"font":{"size":8,"name":"华文中宋"},"align":"center","color":"#262626","bgcolor":"#f1f9f6"},{"border":{"bottom":["thin","#bfbfbf"],"top":["thin","#bfbfbf"],"left":["thin","#bfbfbf"],"right":["thin","#bfbfbf"]},"font":{"size":8,"name":"Arial"},"align":"center","color":"#262626","bgcolor":"#f1f9f6"},{"border":{"bottom":["thin","#bfbfbf"],"top":["thin","#bfbfbf"],"left":["thin","#bfbfbf"],"right":["thin","#bfbfbf"]},"font":{"size":10}},{"border":{"bottom":["thin","#bfbfbf"],"top":["thin","#bfbfbf"],"left":["thin","#bfbfbf"],"right":["thin","#bfbfbf"]},"font":{"size":8},"bgcolor":"#"},{"border":{"bottom":["thin","#bfbfbf"],"top":["thin","#bfbfbf"],"left":["thin","#bfbfbf"],"right":["thin","#bfbfbf"]},"bgcolor":"#"},{"border":{"bottom":["thin","#bfbfbf"],"top":["thin","#bfbfbf"],"left":["thin","#bfbfbf"],"right":["thin","#bfbfbf"]},"font":{"size":8,"name":"Microsoft YaHei"},"align":"center","color":"#262626","bgcolor":"#aedac8"},{"border":{"bottom":["thin","#bfbfbf"],"top":["thin","#bfbfbf"],"left":["thin","#bfbfbf"],"right":["thin","#bfbfbf"]},"font":{"size":8},"bgcolor":"#aedac8"},{"border":{"bottom":["thin","#bfbfbf"],"top":["thin","#bfbfbf"],"left":["thin","#bfbfbf"],"right":["thin","#bfbfbf"]},"bgcolor":"#aedac8"},{"border":{"bottom":["thin","#bfbfbf"],"top":["thin","#bfbfbf"],"left":["thin","#bfbfbf"],"right":["thin","#bfbfbf"]},"font":{"size":8},"bgcolor":"#aedac8","align":"center"},{"border":{"bottom":["thin","#bfbfbf"],"top":["thin","#bfbfbf"],"left":["thin","#bfbfbf"],"right":["thin","#bfbfbf"]},"font":{"size":8},"bgcolor":"#aedac8","align":"center","format":"number"},{"border":{"bottom":["thin","#bfbfbf"],"top":["thin","#bfbfbf"],"left":["thin","#bfbfbf"],"right":["thin","#bfbfbf"]},"font":{"size":8},"bgcolor":"#aedac8","align":"center","format":"normal"},{"border":{"bottom":["thin","#bfbfbf"],"top":["thin","#bfbfbf"],"left":["thin","#bfbfbf"],"right":["thin","#bfbfbf"]},"bgcolor":"#aedac8","align":"center"},{"align":"center","bgcolor":"#02a274","color":"#ffffff","border":{"bottom":["thin","#bfbfbf"],"top":["thin","#bfbfbf"],"left":["thin","#bfbfbf"],"right":["thin","#bfbfbf"]},"font":{"bold":false,"size":9}},{"align":"center","bgcolor":"#02a274","color":"#ffffff","font":{"bold":false,"size":9}},{"border":{"bottom":["thin","#bfbfbf"],"top":["thin","#bfbfbf"],"left":["thin","#bfbfbf"],"right":["thin","#bfbfbf"]},"font":{"size":10,"name":"Microsoft YaHei"},"align":"center","color":"#262626","bgcolor":"#aedac8"},{"font":{"size":10}},{"border":{"bottom":["thin","#bfbfbf"],"top":["thin","#bfbfbf"],"left":["thin","#bfbfbf"],"right":["thin","#bfbfbf"]},"font":{"size":10},"bgcolor":"#aedac8","align":"center","format":"normal"},{"border":{"bottom":["thin","#bfbfbf"],"top":["thin","#bfbfbf"],"left":["thin","#bfbfbf"],"right":["thin","#bfbfbf"]},"font":{"size":10},"bgcolor":"#aedac8","align":"center"},{"border":{"bottom":["thin","#bfbfbf"],"top":["thin","#bfbfbf"],"left":["thin","#bfbfbf"],"right":["thin","#bfbfbf"]},"bgcolor":"#aedac8","font":{"size":10}},{"font":{"size":10},"bgcolor":"#aedac8"},{"align":"center","bgcolor":"#02a274","color":"#ffffff","border":{"bottom":["thin","#bfbfbf"],"top":["thin","#bfbfbf"],"left":["thin","#bfbfbf"],"right":["thin","#bfbfbf"]},"font":{"bold":false,"size":10}},{"align":"center","bgcolor":"#02a274","color":"#ffffff","font":{"bold":false,"size":10}},{"border":{"bottom":["thin","#bfbfbf"],"top":["thin","#bfbfbf"],"left":["thin","#bfbfbf"],"right":["thin","#bfbfbf"]},"font":{"size":10,"name":"Microsoft YaHei"},"align":"center","color":"#262626","bgcolor":"#f1f9f6"},{"border":{"bottom":["thin","#bfbfbf"],"top":["thin","#bfbfbf"],"left":["thin","#bfbfbf"],"right":["thin","#bfbfbf"]},"font":{"size":10,"name":"Microsoft YaHei"},"align":"center","color":"#262626","bgcolor":"#ddefe8"},{"border":{"bottom":["thin","#bfbfbf"],"top":["thin","#bfbfbf"],"left":["thin","#bfbfbf"],"right":["thin","#bfbfbf"]},"font":{"size":10,"name":"Microsoft YaHei"},"align":"center","color":"#262626"},{"border":{"bottom":["thin","#bfbfbf"],"top":["thin","#bfbfbf"],"left":["thin","#bfbfbf"],"right":["thin","#bfbfbf"]},"font":{"size":10,"name":"Microsoft YaHei"},"align":"center"},{"font":{"size":8}},{"border":{"bottom":["thin","#bfbfbf"],"top":["thin","#bfbfbf"],"left":["thin","#bfbfbf"],"right":["thin","#bfbfbf"]},"font":{"size":9,"name":"Microsoft YaHei"},"align":"center","color":"#262626","bgcolor":"#f1f9f6"},{"border":{"bottom":["thin","#bfbfbf"],"top":["thin","#bfbfbf"],"left":["thin","#bfbfbf"],"right":["thin","#bfbfbf"]},"font":{"size":9,"name":"Microsoft YaHei"},"align":"center","color":"#262626","bgcolor":"#ddefe8"},{"align":"center","bgcolor":"#02a274","color":"#ffffff","border":{"bottom":["thin","#bfbfbf"],"top":["thin","#bfbfbf"],"left":["thin","#bfbfbf"],"right":["thin","#bfbfbf"]},"font":{"bold":false,"size":10,"name":"宋体"}},{"align":"center","bgcolor":"#02a274","color":"#ffffff","font":{"bold":false,"size":10,"name":"宋体"}},{"border":{"bottom":["thin","#bfbfbf"],"top":["thin","#bfbfbf"],"left":["thin","#bfbfbf"],"right":["thin","#bfbfbf"]},"font":{"size":9,"name":"宋体"},"align":"center","color":"#262626","bgcolor":"#f1f9f6"},{"border":{"bottom":["thin","#bfbfbf"],"top":["thin","#bfbfbf"],"left":["thin","#bfbfbf"],"right":["thin","#bfbfbf"]},"font":{"size":9,"name":"宋体"},"align":"center","color":"#262626","bgcolor":"#ddefe8"},{"border":{"bottom":["thin","#bfbfbf"],"top":["thin","#bfbfbf"],"left":["thin","#bfbfbf"],"right":["thin","#bfbfbf"]},"font":{"size":8,"name":"宋体"},"align":"center","color":"#262626"},{"border":{"bottom":["thin","#bfbfbf"],"top":["thin","#bfbfbf"],"left":["thin","#bfbfbf"],"right":["thin","#bfbfbf"]},"font":{"size":10,"name":"宋体"},"align":"center","color":"#262626","bgcolor":"#aedac8"},{"font":{"name":"宋体"}},{"border":{"bottom":["thin","#bfbfbf"],"top":["thin","#bfbfbf"],"left":["thin","#bfbfbf"],"right":["thin","#bfbfbf"]},"font":{"size":10,"name":"宋体"},"bgcolor":"#aedac8","align":"center","format":"normal"},{"border":{"bottom":["thin","#bfbfbf"],"top":["thin","#bfbfbf"],"left":["thin","#bfbfbf"],"right":["thin","#bfbfbf"]},"font":{"size":10,"name":"宋体"},"bgcolor":"#aedac8","align":"center"},{"border":{"bottom":["thin","#bfbfbf"],"top":["thin","#bfbfbf"],"left":["thin","#bfbfbf"],"right":["thin","#bfbfbf"]},"bgcolor":"#aedac8","font":{"size":10,"name":"宋体"}},{"font":{"name":"Microsoft YaHei"}},{"align":"center","bgcolor":"#02a274","color":"#ffffff","border":{"bottom":["thin","#bfbfbf"],"top":["thin","#bfbfbf"],"left":["thin","#bfbfbf"],"right":["thin","#bfbfbf"]},"font":{"bold":false,"size":10,"name":"Microsoft YaHei"}},{"align":"center","bgcolor":"#02a274","color":"#ffffff","font":{"bold":false,"size":10,"name":"Microsoft YaHei"}},{"font":{"size":8,"name":"Microsoft YaHei"}},{"border":{"bottom":["thin","#bfbfbf"],"top":["thin","#bfbfbf"],"left":["thin","#bfbfbf"],"right":["thin","#bfbfbf"]},"font":{"size":10,"name":"Microsoft YaHei"},"bgcolor":"#aedac8","align":"center","format":"normal"},{"border":{"bottom":["thin","#bfbfbf"],"top":["thin","#bfbfbf"],"left":["thin","#bfbfbf"],"right":["thin","#bfbfbf"]},"font":{"size":10,"name":"Microsoft YaHei"},"bgcolor":"#aedac8","align":"center"},{"border":{"bottom":["thin","#bfbfbf"],"top":["thin","#bfbfbf"],"left":["thin","#bfbfbf"],"right":["thin","#bfbfbf"]},"bgcolor":"#aedac8","font":{"size":10,"name":"Microsoft YaHei"}}],"validations":[],"isGroup":true,"cols":{"0":{"width":20},"1":{"width":84},"2":{"width":81},"3":{"width":75},"4":{"width":63},"5":{"width":59},"6":{"width":70},"7":{"width":57},"8":{"width":60},"9":{"width":75},"10":{"width":66},"11":{"width":64},"12":{"width":70},"13":{"width":61},"14":{"width":61},"15":{"width":70},"16":{"width":58},"17":{"width":63},"18":{"width":60},"19":{"width":63},"20":{"width":59},"21":{"width":73},"22":{"width":69},"23":{"width":73},"len":50},"merges":["B2:B3","C2:C3","D2:F2","G2:I2","J2:L2","M2:O2","P2:R2","S2:U2","V2:X2","B1:X1","B5:C5"]}
2021-04-07 11:26:18.298 ERROR 9624 --- [nio-9991-exec-4] o.jeecg.modules.jmreport.desreport.a.a   : No qualifying bean of type 'org.jeecg.modules.jmreport.api.JmReportTokenServiceI' available

org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'org.jeecg.modules.jmreport.api.JmReportTokenServiceI' available
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBean(DefaultListableBeanFactory.java:351) ~[spring-beans-5.3.3.jar:5.3.3]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBean(DefaultListableBeanFactory.java:342) ~[spring-beans-5.3.3.jar:5.3.3]
	at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1177) ~[spring-context-5.3.3.jar:5.3.3]
	at org.jeecg.modules.jmreport.common.util.JimuSpringContextUtils.getBean(JimuSpringContextUtils.java:65) ~[spring-boot-starter-jimureport-1.3.1-beta2.jar:2.0.0]
	at org.jeecg.modules.jmreport.desreport.b.c.a(JmformUtil.java:604) ~[spring-boot-starter-jimureport-1.3.1-beta2.jar:2.0.0]
	at org.jeecg.modules.jmreport.desreport.b.c.b(JmformUtil.java:360) ~[spring-boot-starter-jimureport-1.3.1-beta2.jar:2.0.0]
	at org.jeecg.modules.jmreport.desreport.service.a.d.a(JimuReportServiceImpl.java:2038) ~[spring-boot-starter-jimureport-1.3.1-beta2.jar:2.0.0]
	at org.jeecg.modules.jmreport.desreport.service.a.d.getDataById(JimuReportServiceImpl.java:329) ~[spring-boot-starter-jimureport-1.3.1-beta2.jar:2.0.0]
	at org.jeecg.modules.jmreport.desreport.service.a.d.show(JimuReportServiceImpl.java:2361) ~[spring-boot-starter-jimureport-1.3.1-beta2.jar:2.0.0]
	at org.jeecg.modules.jmreport.desreport.service.a.d$$FastClassBySpringCGLIB$$4daca650.invoke(<generated>) ~[spring-boot-starter-jimureport-1.3.1-beta2.jar:2.0.0]
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) ~[spring-core-5.3.3.jar:5.3.3]
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:688) ~[spring-aop-5.3.3.jar:5.3.3]
	at org.jeecg.modules.jmreport.desreport.service.a.d$$EnhancerBySpringCGLIB$$8248c8d.show(<generated>) ~[spring-boot-starter-jimureport-1.3.1-beta2.jar:2.0.0]
	at org.jeecg.modules.jmreport.desreport.a.a.a(DesignReportController.java:304) ~[spring-boot-starter-jimureport-1.3.1-beta2.jar:2.0.0]
	at sun.reflect.GeneratedMethodAccessor227.invoke(Unknown Source) ~[na:na]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_131]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_131]
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:197) [spring-web-5.3.3.jar:5.3.3]
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:141) [spring-web-5.3.3.jar:5.3.3]
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:106) [spring-webmvc-5.3.3.jar:5.3.3]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:894) [spring-webmvc-5.3.3.jar:5.3.3]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:808) [spring-webmvc-5.3.3.jar:5.3.3]
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87) [spring-webmvc-5.3.3.jar:5.3.3]
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1060) [spring-webmvc-5.3.3.jar:5.3.3]
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:962) [spring-webmvc-5.3.3.jar:5.3.3]
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006) [spring-webmvc-5.3.3.jar:5.3.3]
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:898) [spring-webmvc-5.3.3.jar:5.3.3]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:497) [jakarta.servlet-api-4.0.4.jar:4.0.4]
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883) [spring-webmvc-5.3.3.jar:5.3.3]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:584) [jakarta.servlet-api-4.0.4.jar:4.0.4]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231) [tomcat-embed-core-9.0.41.jar:9.0.41]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-9.0.41.jar:9.0.41]
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100) [spring-web-5.3.3.jar:5.3.3]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) [spring-web-5.3.3.jar:5.3.3]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat-embed-core-9.0.41.jar:9.0.41]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-9.0.41.jar:9.0.41]
	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93) [spring-web-5.3.3.jar:5.3.3]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) [spring-web-5.3.3.jar:5.3.3]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat-embed-core-9.0.41.jar:9.0.41]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-9.0.41.jar:9.0.41]
	at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:93) [spring-boot-actuator-2.4.2.jar:2.4.2]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) [spring-web-5.3.3.jar:5.3.3]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat-embed-core-9.0.41.jar:9.0.41]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-9.0.41.jar:9.0.41]
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201) [spring-web-5.3.3.jar:5.3.3]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) [spring-web-5.3.3.jar:5.3.3]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat-embed-core-9.0.41.jar:9.0.41]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-9.0.41.jar:9.0.41]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202) [tomcat-embed-core-9.0.41.jar:9.0.41]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97) [tomcat-embed-core-9.0.41.jar:9.0.41]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:542) [tomcat-embed-core-9.0.41.jar:9.0.41]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:143) [tomcat-embed-core-9.0.41.jar:9.0.41]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92) [tomcat-embed-core-9.0.41.jar:9.0.41]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78) [tomcat-embed-core-9.0.41.jar:9.0.41]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343) [tomcat-embed-core-9.0.41.jar:9.0.41]
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:374) [tomcat-embed-core-9.0.41.jar:9.0.41]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65) [tomcat-embed-core-9.0.41.jar:9.0.41]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:888) [tomcat-embed-core-9.0.41.jar:9.0.41]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1597) [tomcat-embed-core-9.0.41.jar:9.0.41]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat-embed-core-9.0.41.jar:9.0.41]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_131]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_131]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-embed-core-9.0.41.jar:9.0.41]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_131]

**Comment by lcc-java** [comment]
尝试过 api 解释完 之后  没有数据返回的 都会报这个问题

**Comment by zhangdaiscott** [comment]
升级到1.3.1-beta3看看

**Comment by lcc-java** [comment]
好的 谢谢
