### ISSUE TITLE
关于使用druid 和mybatis 结合出现

### ISSUE THREAD

**Issue by guren1131** [zhangdaiscott/JimuReport#215]
##### 版本号：
1.3.2-beta

##### 问题描述：

![image](https://user-images.githubusercontent.com/32631049/115509919-a1a83a80-a2b1-11eb-8b39-a89cc804069f.png)

##### 截图&代码：

g.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'designReportController': Unsatisfied dependency expressed through field 'jmReportDesignService'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'jimuReportServiceImpl' defined in URL [jar:file:/C:/Users/IYU00101/.m2/repository/org/jeecgframework/jimureport/spring-boot-starter-jimureport/1.3.2-beta/spring-boot-starter-jimureport-1.3.2-beta.jar!/org/jeecg/modules/jmreport/desreport/service/a/d.class]: Initialization of bean failed; nested exception is org.springframework.aop.framework.AopConfigException: Unexpected AOP exception; nested exception is java.lang.IllegalStateException: Unable to load cache item
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:643)
	at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:130)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessProperties(AutowiredAnnotationBeanPostProcessor.java:399)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1422)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.ja

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by guren1131** [comment]
已经配置 scanBasePackages = {"org.jeecg.modules.jmreport"}

**Comment by zhangdaiscott** [comment]
有更详细的错误吗？群里其他人没反馈有问题啊，应该还是你本地有什么特殊的

**Comment by guren1131** [comment]
13:33:55.090 [restartedMain] INFO  o.j.m.f.MiniDaoClassPathMapperScanner - [doScan,48] - register minidao name is { org.jeecg.modules.jmreport.desreport.dao.JimuReportDao }
13:33:55.091 [restartedMain] INFO  o.j.m.f.MiniDaoClassPathMapperScanner - [doScan,48] - register minidao name is { org.jeecg.modules.jmreport.desreport.dao.JimuReportDataSourceDao }
13:33:55.091 [restartedMain] INFO  o.j.m.f.MiniDaoClassPathMapperScanner - [doScan,48] - register minidao name is { org.jeecg.modules.jmreport.desreport.dao.JimuReportDbDao }
13:33:55.091 [restartedMain] INFO  o.j.m.f.MiniDaoClassPathMapperScanner - [doScan,48] - register minidao name is { org.jeecg.modules.jmreport.desreport.dao.JimuReportDbFieldDao }
13:33:55.091 [restartedMain] INFO  o.j.m.f.MiniDaoClassPathMapperScanner - [doScan,48] - register minidao name is { org.jeecg.modules.jmreport.desreport.dao.JimuReportDbParamDao }
13:33:55.091 [restartedMain] INFO  o.j.m.f.MiniDaoClassPathMapperScanner - [doScan,48] - register minidao name is { org.jeecg.modules.jmreport.desreport.dao.JimuReportDictDao }
13:33:55.091 [restartedMain] INFO  o.j.m.f.MiniDaoClassPathMapperScanner - [doScan,48] - register minidao name is { org.jeecg.modules.jmreport.desreport.dao.JimuReportDictItemDao }
13:33:55.091 [restartedMain] INFO  o.j.m.f.MiniDaoClassPathMapperScanner - [doScan,48] - register minidao name is { org.jeecg.modules.jmreport.desreport.dao.JimuReportLinkDao }
13:33:55.091 [restartedMain] INFO  o.j.m.f.MiniDaoClassPathMapperScanner - [doScan,48] - register minidao name is { org.jeecg.modules.jmreport.desreport.dao.JimuReportMapDao }
13:33:55.092 [restartedMain] INFO  o.j.m.f.MiniDaoClassPathMapperScanner - [doScan,48] - register minidao name is { org.jeecg.modules.jmreport.desreport.dao.JimuReportShareDao }
13:33:56.125 [restartedMain] INFO  o.a.c.h.Http11NioProtocol - [log,173] - Initializing ProtocolHandler ["http-nio-8080"]
13:33:56.125 [restartedMain] INFO  o.a.c.c.StandardService - [log,173] - Starting service [Tomcat]
13:33:56.125 [restartedMain] INFO  o.a.c.c.StandardEngine - [log,173] - Starting Servlet engine: [Apache Tomcat/9.0.31]
13:33:56.298 [restartedMain] INFO  o.a.c.c.C.[.[.[/] - [log,173] - Initializing Spring embedded WebApplicationContext
13:33:56.772 [restartedMain] DEBUG c.j.f.s.f.JwtAuthenticationTokenFilter - [init,242] - Filter 'jwtAuthenticationTokenFilter' configured for use
13:33:56.800 [restartedMain] INFO  o.j.m.j.c.JimuReportConfiguration - [afterPropertiesSet,47] -  --- Init JimuReport Config --- 
13:33:56.924 [restartedMain] WARN  o.s.b.w.s.c.AnnotationConfigServletWebServerApplicationContext - [refresh,558] - Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'designReportController': Unsatisfied dependency expressed through field 'jmReportDesignService'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'jimuReportServiceImpl' defined in URL [jar:file:/C:/Users/IYU00101/.m2/repository/org/jeecgframework/jimureport/spring-boot-starter-jimureport/1.3.1-beta/spring-boot-starter-jimureport-1.3.1-beta.jar!/org/jeecg/modules/jmreport/desreport/service/a/d.class]: Initialization of bean failed; nested exception is org.springframework.aop.framework.AopConfigException: Unexpected AOP exception; nested exception is java.lang.IllegalStateException: Unable to load cache item
13:33:56.941 [restartedMain] INFO  c.a.d.p.DruidDataSource - [close,2029] - {dataSource-0} closing ...
13:33:56.943 [restartedMain] INFO  o.a.c.c.StandardService - [log,173] - Stopping service [Tomcat]
13:33:56.967 [restartedMain] ERROR o.s.b.SpringApplication - [reportFailure,826] - Application run failed
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'designReportController': Unsatisfied dependency expressed through field 'jmReportDesignService'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'jimuReportServiceImpl' defined in URL [jar:file:/C:/Users/IYU00101/.m2/repository/org/jeecgframework/jimureport/spring-boot-starter-jimureport/1.3.1-beta/spring-boot-starter-jimureport-1.3.1-beta.jar!/org/jeecg/modules/jmreport/desreport/service/a/d.class]: Initialization of bean failed; nested exception is org.springframework.aop.framework.AopConfigException: Unexpected AOP exception; nested exception is java.lang.IllegalStateException: Unable to load cache item
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:643)
	at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:130)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessProperties(AutowiredAnnotationBeanPostProcessor.java:399)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1422)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:594)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:517)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:323)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:321)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:879)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:878)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:550)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:141)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:747)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:315)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1215)
	at com.jeethink.JeeThinkApplication.main(JeeThinkApplication.java:22)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.boot.devtools.restart.RestartLauncher.run(RestartLauncher.java:49)
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'jimuReportServiceImpl' defined in URL [jar:file:/C:/Users/IYU00101/.m2/repository/org/jeecgframework/jimureport/spring-boot-starter-jimureport/1.3.1-beta/spring-boot-starter-jimureport-1.3.1-beta.jar!/org/jeecg/modules/jmreport/desreport/service/a/d.class]: Initialization of bean failed; nested exception is org.springframework.aop.framework.AopConfigException: Unexpected AOP exception; nested exception is java.lang.IllegalStateException: Unable to load cache item
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:603)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:517)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:323)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:321)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:276)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1287)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1207)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:640)
	... 24 common frames omitted
Caused by: org.springframework.aop.framework.AopConfigException: Unexpected AOP exception; nested exception is java.lang.IllegalStateException: Unable to load cache item
	at org.springframework.aop.framework.CglibAopProxy.getProxy(CglibAopProxy.java:214)
	at org.springframework.aop.framework.ProxyFactory.getProxy(ProxyFactory.java:110)
	at org.springframework.aop.framework.autoproxy.AbstractAutoProxyCreator.createProxy(AbstractAutoProxyCreator.java:471)
	at org.springframework.aop.framework.autoproxy.AbstractAutoProxyCreator.wrapIfNecessary(AbstractAutoProxyCreator.java:350)
	at org.springframework.aop.framework.autoproxy.AbstractAutoProxyCreator.postProcessAfterInitialization(AbstractAutoProxyCreator.java:299)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsAfterInitialization(AbstractAutowireCapableBeanFactory.java:431)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1800)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:595)
	... 33 common frames omitted
Caused by: java.lang.IllegalStateException: Unable to load cache item
	at org.springframework.cglib.core.internal.LoadingCache.createEntry(LoadingCache.java:79)
	at org.springframework.cglib.core.internal.LoadingCache.get(LoadingCache.java:34)
	at org.springframework.cglib.core.AbstractClassGenerator$ClassLoaderData.get(AbstractClassGenerator.java:134)
	at org.springframework.cglib.core.AbstractClassGenerator.create(AbstractClassGenerator.java:319)
	at org.springframework.cglib.proxy.Enhancer.createHelper(Enhancer.java:569)
	at org.springframework.cglib.proxy.Enhancer.createClass(Enhancer.java:416)
	at org.springframework.aop.framework.ObjenesisCglibAopProxy.createProxyClassAndInstance(ObjenesisCglibAopProxy.java:57)
	at org.springframework.aop.framework.CglibAopProxy.getProxy(CglibAopProxy.java:205)
	... 40 common frames omitted
Caused by: java.lang.LinkageError: loader constraint violation: when resolving overridden method "org.jeecg.modules.jmreport.desreport.service.a.d$$EnhancerBySpringCGLIB$$1e4f6890.addChart(Ljava/lang/String;)Lcom/alibaba/fastjson/JSONObject;" the class loader (instance of org/springframework/boot/devtools/restart/classloader/RestartClassLoader) of the current class, org/jeecg/modules/jmreport/desreport/service/a/d$$EnhancerBySpringCGLIB$$1e4f6890, and its superclass loader (instance of sun/misc/Launcher$AppClassLoader), have different Class objects for the type com/alibaba/fastjson/JSONObject used in the signature
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at org.springframework.cglib.core.ReflectUtils.defineClass(ReflectUtils.java:571)
	at org.springframework.cglib.core.AbstractClassGenerator.generate(AbstractClassGenerator.java:363)
	at org.springframework.cglib.proxy.Enhancer.generate(Enhancer.java:582)
	at org.springframework.cglib.core.AbstractClassGenerator$ClassLoaderData$3.apply(AbstractClassGenerator.java:110)
	at org.springframework.cglib.core.AbstractClassGenerator$ClassLoaderData$3.apply(AbstractClassGenerator.java:108)
	at org.springframework.cglib.core.internal.LoadingCache$2.call(LoadingCache.java:54)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at org.springframework.cglib.core.internal.LoadingCache.createEntry(LoadingCache.java:61)
	... 47 common frames omitted

Process finished with exit code 1

**Comment by zhangdaiscott** [comment]
have different Class objects for the type com/alibaba/fastjson/JSONObject used in the signature

这不明显版本号不一致吗

**Comment by guren1131** [comment]
关键的 fastjson版本号是一致的 1.2.75

**Comment by Gowther** [comment]
> 关键的 fastjson版本号是一致的 1.2.75

我也碰到这个问题，应该是和spring boot devtools有关系。我把pom里的spring-boot-devtools依赖去掉就不报错了
