### ISSUE TITLE
点击积木报表设计菜单时token=null

### ISSUE THREAD

**Issue by freedomme** [zhangdaiscott/JimuReport#335]
##### 截图&代码：
后台 异常代码：
org.apache.shiro.authc.AuthenticationException: token非法无效!
	at org.jeecg.common.util.TokenUtils.verifyToken(TokenUtils.java:109)
	at org.jeecg.config.jimureport.JimuReportTokenService.verifyToken(JimuReportTokenService.java:43)
	at org.jeecg.modules.jmreport.config.client.JmReportTokenClient.verifyToken(JmReportTokenClient.java:117)
	at org.jeecg.modules.jmreport.common.interceptor.JimuReportInterceptor.verifyToken(JimuReportInterceptor.java:63)
	at org.jeecg.modules.jmreport.common.interceptor.JimuReportInterceptor.preHandle(JimuReportInterceptor.java:47)
	at org.springframework.web.servlet.HandlerExecutionChain.applyPreHandle(HandlerExecutionChain.java:151)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1035)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:943)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:898)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:626)

**Comment by zhangdaiscott** [comment]
截图

**Comment by freedomme** [comment]
感谢作者大神回复。
![image](https://user-images.githubusercontent.com/6744887/123185559-ca72c900-d4c8-11eb-8383-7b91938dc1cf.png)

**Comment by zhangdaiscott** [comment]
传递有效token

**Comment by zhangxinyuan1** [comment]
@zhangdaiscott 我觉得上面说的是新建报表的时候 token 带不过去，并不是过期的原因吧
