### ISSUE TITLE
使用中的遇到一些问题和建议

### ISSUE THREAD

**Issue by freewind1977** [zhangdaiscott/JimuReport#36]
非常感谢将积木报对外提供使用与集成，一直在关注这个项目的信息，看到1.1beta发布后，做了一些测试并发现一些问题，具体如下，本人真心希望这个项目越来越优秀。

运行环境：
docker desktop k8s以单点方式运行：
版本：
jeecg-boot 2.4.1 (master 2020-12-11)
jimureport 1.1-beta

问题汇总：
1.报表插入图片后，调整大小后，在图片上右键选择设置背景后，图片恢复原有大小，选择其他也是一样；
2.在上述操作后，想更换背景图片，没找到相应功能；
3.新建报表后，进入报表设计器页面，在不保存的情况下点击预览，链接地址为：about:blank
4.新建报表时，选择在数据报表下，但在保存时，对话框默认还是“报表设计”；
5.当报表有图片背景，并选择分页显示后，调整每页显示的条数，背景图片会消失，重新刷新才会再显示；
6.当将数据列拖动不在一行时只显示不在同一条时，只会显示一条数据，此时点击下一页会显示第11条数据；
7.新建数据集，并创建mysql数据源，点击测试，无提示，但可以正常进行sql解析；

对于图片上传的一些建议：
1.现在是每个图片上传图片后，其他报表要再次使用时需要重新上传，一是操作过于麻烦，二是也不便于统一替换，比如：一些通用性的图标/图片，能否采用资源的方式进行管理；
2.图表创建后，输入名称后，在保存时如果存在会提示，让用户选择是覆盖还是取消；如果基于数据防覆盖的考虑，可以在后端数据库中进行历史报表数据的备份；

此外，还有就是在使用jimureport时（/jeecg-boot/jmreport/list），在做上述测试时，后台服务报异常后，虽然前台还可以使用，但操作一会就会导致容器重启（运行环境见问题开始部分)。
错误信息如下：
2020-12-12 20:00:43.839 [http-nio-8080-exec-5] ERROR org.apache.tomcat.websocket.pojo.PojoEndpointBase:175 - No error handling configured for [org.jeecg.modules.message.websocket.WebSocket] and the following error occurred
java.io.EOFException: null
        at org.apache.tomcat.util.net.NioEndpoint$NioSocketWrapper.fillReadBuffer(NioEndpoint.java:1231)
        at org.apache.tomcat.util.net.NioEndpoint$NioSocketWrapper.read(NioEndpoint.java:1141)
        at org.apache.tomcat.websocket.server.WsFrameServer.onDataAvailable(WsFrameServer.java:72)
        at org.apache.tomcat.websocket.server.WsFrameServer.doOnDataAvailable(WsFrameServer.java:171)
        at org.apache.tomcat.websocket.server.WsFrameServer.notifyDataAvailable(WsFrameServer.java:151)
        at org.apache.tomcat.websocket.server.WsHttpUpgradeHandler.upgradeDispatch(WsHttpUpgradeHandler.java:148)
        at org.apache.coyote.http11.upgrade.UpgradeProcessorInternal.dispatch(UpgradeProcessorInternal.java:54)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:59)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1590)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.base/java.lang.Thread.run(Unknown Source)
2020-12-12 20:00:43.840 [http-nio-8080-exec-5] INFO  org.jeecg.modules.message.websocket.WebSocket:51 - 【websocket消息】连接断开，总数为:0
2020-12-12 20:01:44.126 [http-nio-8080-exec-2] INFO  org.jeecg.modules.jmreport.desreport.a.a:809 - ============initDataSource==========
2020-12-12 20:01:44.129 [http-nio-8080-exec-4] INFO  org.jeecg.modules.jmreport.desreport.a.a:764 - ============fieldTree==========
2020-12-12 20:01:44.427 [http-nio-8080-exec-10] INFO  org.jeecg.modules.jmreport.desreport.a.a:1286 - ============地图列表查询==========
2020-12-12 20:01:48.020 [http-nio-8080-exec-10] INFO  org.jeecg.modules.jmreport.desreport.a.a:790 - ============loadDbData==========
2020-12-12 20:01:52.656 [http-nio-8080-exec-9] INFO  org.jeecg.modules.jmreport.desreport.a.a:741 - ============saveDb==========
2020-12-12 20:01:53.323 [http-nio-8080-exec-8] INFO  org.jeecg.modules.jmreport.desreport.a.a:764 - ============fieldTree==========

**Comment by mini2014** [comment]
谢谢，你的建议，我们会采纳的
